database:
  host: "localhost"
  port: 3306
  user: "dantorto_console"
  password: "Danilo2024"
  database_name: "dantorto_ceps"
  table_name: "cep_unificado"

api:
  url_template: "https://cep.awesomeapi.com.br/json/{cep}"

script:
  query_direction: "DESC"  # Define se as consultas serão em ordem crescente (ASC) ou decrescente (DESC)
  sleep_interval: 1  # Pausa entre consultas, em segundos (defina como 0 para sem pausa)
  max_retries: 3  # Número máximo de tentativas em caso de erro
